! This file is generated by FTA 
! Please DO NOT MODIFY IT !!!


module torch_wrapper
    use, intrinsic :: iso_c_binding, only: C_int, C_float
    implicit none

    ! interface for external C function
    interface resnet_call  
        function resnet_call (input) result(r) bind(c, name="resnet_call")
            import
            REAL(C_float) :: input(1, 3, 224, 224)
            INTEGER(C_int) :: r
        end function
    end interface

    contains
        ! function provided by FTA in Fortran environment
        ! The user only needs to care about this function's interface
        !!   which is determined by their configuration
        function call_model (input) result(r)
            REAL(C_float) :: input(1, 3, 224, 224)
            INTEGER(C_int) :: r
            print *, "model call start"
            r = resnet_call(input)
            print *, "model call end"
        end function call_model
    
end module torch_wrapper